name: 'template-json'
description: 'Render json template'
author: 'integraldx@integraldx.me'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  template:
    description: 'Template json string'
    required: true
  values:
    description: 'Values required to render template, as json object'
    required: true

outputs:
  rendered:
    description: 'rendered json string'

runs:
  using: node20
  main: dist/index.js
